### ISSUE TITLE
上架 chrome 商店？

### ISSUE THREAD

**Issue by HaveF** [ZhuPeng/mp-transform-public#1]

**Comment by ZhuPeng** [comment]
嗯嗯，在计划了~

**Comment by ZhuPeng** [comment]
@HaveF 上架了~  [Chrome 应用商店](https://chrome.google.com/webstore/detail/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%8E%92%E7%89%88%E5%B0%8F%E5%8A%A9%E6%89%8B/aigggkimjmfijjfbhonlblgajnoilbbb)

**Comment by HaveF** [comment]
撒花~~
